language: node_js

node_js:
  - "8"

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

install:
  - npm install

script:
  - stty cols 80
  - npm run test:cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
